basePath: /v1
consumes:
- application/json
info:
  contact:
    email: roy.situmorang@gmail.com
    name: Roy Situmorang
  description: This is documentation of Sadia API.
  title: Sadia API
  version: 0.1.0
paths: {}
produces:
- application/json
schemes:
- http
- https
security:
- ApiKeyAuth: []
securityDefinitions:
  apiKey:
    description: Sadia API call requires X-Api-Key request header
    in: header
    name: x-api-key
    type: apiKey
swagger: "2.0"
